services:
  bff-service:
    networks:
      - back-end
    pull_policy: build
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8082:3000'
    env_file:
      - stack.env
    labels:
      prometheus.io/scrape: "true"
      prometheus.io/hostport: "8082"
      prometheus.io/path: "/metrics"
      environment: "production"

networks:
  back-end:
    driver: bridge
