version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    ports:
      - "8080:8080"
    container_name: category-service
    environment:
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
    networks:
      - postgres_default

networks:
  category-service_default:
  postgres_default: