FROM golang:1.23.4

# Set the working directory
WORKDIR /app

# Copy go.mod and go.sum
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the source code
COPY . .

# Set Go environment variables
ENV CGO_ENABLED=0 GO111MODULE=on GOPATH=/go PATH=$GOPATH/bin:$PATH

# Install system tools and dependencies
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

# Build the application
RUN go build -o main main.go

# Expose the application port
EXPOSE 8080

# Run the application
CMD ["./main"]
