version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    ports:
      - "8080:8080"
    container_name: category-service
    env_file:
      - stack.env